export const OPENING_CHECKLIST = [
  'Turn on espresso machine and allow to heat',
  'Flush group heads 3 times each',
  'Run calibration / dial-in espresso shot',
  'Check milk stock in fridge (cow, oat, soy)',
  'Wipe steam wand inside and out',
  'Prime and purge steam wand',
  'Fill and position portafilters',
  'Check bean hopper — refill if under 300g',
  'Stock cups at counter (small, medium, large)',
  'Stock lids and straws',
  'Prepare and display pastries in case',
  'Check syrup bottles — refill if under ¼',
  'Check ice bin — fill if under half',
  'Wipe counter, bar top and display surfaces',
  'Check cash drawer — confirm opening float',
  'Ensure QR code poster is visible',
  'Check blender is clean and ready',
  'Prepare boba pearls if needed',
  'Ice cream tubs in freezer — confirm count',
  'Unlock shutter / open sign on',
];

export const CLOSING_CHECKLIST = [
  'Turn off espresso machine',
  'Backflush group heads with cleaner tablet',
  'Clean and store portafilters',
  'Empty and rinse drip trays',
  'Wipe down steam wand thoroughly',
  'Clean blender and store',
  'Dispose of unsold pastries / wrap for donation',
  'Store leftover milk (labelled with date)',
  'Count and record closing cash',
  'Wipe all surfaces — bar, counter, display',
  'Empty bins and replace liners',
  'Mop floor behind counter',
  'Turn off music, lights, fans',
  'Lock up / pull down shutter',
];
